feat(IaC): adding pulumi for managing infrastructure
sotex-lab/sotex-box pull request #13
Opened 2024-02-24 16:46 UTC by NikolaMilosa

**Description**:

In this pull request the pulumi tool has been introduced for managing infrastructure. This ticket is related to setting up of the tool and deploying a simple `nginx` image to AWS. Further PR's will setup the concrete deploying of our stack. Closes #12 

**Checklist**:

- [x] ~Unit tests: Have you added or updated unit tests for your changes and do you need to?~ Pulumi does support unit tests and integration tests. This should be made into a ticket as an extension point once we have our stack deployed.
- [x] ~Integration tests: Have you added or updated integration tests and do you need to?~ Same as above
- [x] ~Bechmarks: Have you added benchmarks and if so did you run them?~ Not needed
- [x] Documentation: Have you update the relevant documentation to reflect the changes?

2024-02-24 16:47 UTC, NikolaMilosa commented
Pending to add: Github CI that runs preview if there are changes in infra folder.

2024-02-25 20:50 UTC, AleksaBajat requested changes
Typo, and region changes.

2024-02-25 20:50 UTC, AleksaBajat commented on infra/backend/Pulumi.staging.yaml
eu-central-1 might be better since it has lower latency.
https://clients.amazonworkspaces.com/Health.html
https://cloudping.info/

2024-02-25 20:50 UTC, AleksaBajat commented on infra/backend/Pulumi.yaml
> +    description: To which porn on host to map
Typo..

2024-02-25 20:50 UTC, AleksaBajat commented on infra/backend/Pulumi.yaml
> +      - eu-north-1a
eu-central

2024-02-26 06:06 UTC, NikolaMilosa commented on infra/backend/Pulumi.staging.yaml
Must have missed [this](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate-Regions.html). Seems we can deploy Fargate to `eu-central`. Changing. Thanks!

2024-02-26 09:10 UTC, AleksaBajat approved these changes
Nice!

2024-02-26 09:13 UTC, merged