feat(splash-screen): Sotex Solutions Splash Screen
sotex-lab/sotex-box pull request #35
Opened 2024-03-28 11:52 UTC by AleksaBajat

**Description**:

Added Sotex Solutions splash screen to the launcher.

**Checklist**:

- [ ] Unit tests: Have you added or updated unit tests for your changes and do you need to?
- [ ] Integration tests: Have you added or updated integration tests and do you need to?
- [ ] Bechmarks: Have you added benchmarks and if so did you run them?
- [ ] Documentation: Have you update the relevant documentation to reflect the changes?

2024-03-28 14:18 UTC, NikolaMilosa submitted a review, later dismissed
Overall nice work. For me to work I needed to (after installing cmd tools from the link) move the path of cmd tools to a path like in this [stackoverflow answer](https://stackoverflow.com/a/67413427). After that I had to set the ANDROID_HOME env variable and it started working. On top of that there are some essential things missing in Makefile:
```bash
ANDROID_IMAGE := "system-images;android-31;android-tv;x86"
BUILD_TOOLS := "build-tools;31.0.0"
PLATFORMS := "platforms;android-31"
.PHONY: flutter-create-emulator
flutter-create-emulator: ## Shorthand for setting up an emulator
	sdkmanager $(BUILD_TOOLS)
	sdkmanager $(PLATFORMS)
	sdkmanager $(ANDROID_IMAGE)
	sdkmanager emulator
	sdkmanager platform-tools
	avdmanager create avd -n "android_tv" -k $(ANDROID_IMAGE) --force
```

Please document the stackoverflow answer somehow. Maybe adding a Troubleshoot page for android would be good

2024-04-05 12:40 UTC, NikolaMilosa approved these changes
Seems great!

2024-04-05 12:40 UTC, NikolaMilosa commented on android/launcher/lib/main.dart
> +    Future.delayed(const Duration(milliseconds: 3600), () {
Can we make these magic numbers configurable? IE maybe for dev env I would like to have no delay? These need to be related to "build" config, rather than "runtime" config. Not sure if there are such things in flutter although I don't see why that wouldn't be possible.

2024-04-05 13:49 UTC, AleksaBajat commented on android/launcher/lib/main.dart
> +    Future.delayed(const Duration(milliseconds: 3600), () {
You can configure magic right now  :magic_wand: !

2024-04-05 15:36 UTC, NikolaMilosa requested changes

2024-04-05 15:36 UTC, NikolaMilosa commented on android/launcher/android/app/src/main/kotlin/com/example/launcher/MainActivity.kt
> +        // intent.putExtra("background_mode", transparent.toString())
nit: Remove comment

2024-04-05 15:36 UTC, NikolaMilosa commented on android/launcher/lib/logging.dart
> +    printer: SimplePrinter());
Log level should be configurable as well. What i suggest is checking if something is present in the `.env` and if not put it on default `info`

2024-04-05 15:36 UTC, NikolaMilosa commented on android/launcher/lib/safe_casting.dart
> +}
Generally not advisable to do a "best effort" and to "guess" what somebody wanted. If you cannot parse, either panic or return false and exit. It is expected of a device to be configured properly

2024-04-10 22:15 UTC, NikolaMilosa approved these changes
✅

2024-04-11 08:13 UTC, merged